### ISSUE TITLE
Address binding of request to response

### ISSUE THREAD

**Issue by GrumpyOldTroll** [squarooticus/draft-krose-multicast-security#12]
Comment from EKR on secdispatch:
> S 3.2.
>
>    The Web security model requires that content be authenticated
>    cryptographically.  In the context of unicast transport security,
>    authentication means that content is known to have originated from
>    the trusted peer, something that is typically enforced via a
>    cryptographic authentication tag:
>
> This is true, but I think misses an important property of Web
> authentication, which is the binding between the request and
> the response. I.e., the property is not just that the message
> came from the peer but also that it came in response to a given
> request.

**Comment by squarooticus** [comment]
@GrumpyOldTroll The PR isn't ready yet, but I have to run for now and I wanted you to look at what I've started to put together. Comments welcome on the above commit.
