### ISSUE TITLE
Too dismissive of replay in Authenticity and Integrity section

### ISSUE THREAD

**Issue by GrumpyOldTroll** [squarooticus/draft-krose-multicast-security#3]
last paragraph of section 4.1 maybe should talk about replay mitigation and loss detection, which is probably doable in both ambi and tesla.

**Comment by squarooticus** [comment]
Unless I'm misunderstanding something about TESLA (which is entirely possible since I've never read the doc completely through), it doesn't have any structure in which duplication/replay/reordering would be detectable within a time interval, nor indeed anything at all for loss/deletion.
