### ISSUE TITLE
Amplification attack vector?

### ISSUE THREAD

**Issue by squarooticus** [squarooticus/draft-krose-multicast-security#9]
You had this:

> TODO: maybe some mention that higher-level protocols can provide reliability (e.g. 5740 (norm)/5775 (alc) and/or flute(6726)/fcast(6968) that use alc, plus draft-pardue-quic-http-mcast), but this may introduce different risks from spoofing if per-packet authenticity is not provided.  For example, in an application with unicast recovery for a reliable object that's constructed out of 1k packets, injecting a single spoofed packet amplifies by 1k * number of receivers, if they all recover the whole reliable object.  Also: determine whether this mention belongs in this section--maybe better as a ref to a different section here?

I don't understand what is being suggested here. How does injection cause all the clients to generate recovery requests?

**Comment by GrumpyOldTroll** [comment]
Here I'm talking about mechanisms that build a block out of unauthenticated packets, and then the block gets authenticated as a whole.

If injecting a packet causes a successful build of a block that fails authentication, then users would fall back to another method to recover the block, for example fetching it with unicast.

So when the superbowl is on and you're using 1.4MB segments (composed of ~1k packets each), then someone injects a spoofed packet that causes a mistaken build of the segment, everybody has to get that missed segment at the same time and it messes everything up.  By providing per-packet authentication, you can prevent the attempt to construct a block using a bad packet, and thus prevent the invalidating of 999 other packets that had been legitimately received.

**Comment by squarooticus** [comment]
Got it.

**Comment by squarooticus** [comment]
Right, so it's actually 1.4 MB * number of receivers, not 1 KB (in the case you're talking about).

**Comment by GrumpyOldTroll** [comment]
1k packets * packet size * number of receivers.  Yes.

Segments can of course also be bigger, but as an example 1000 packets per segment is not unreasonably low or high.  Probably on the lower side, I guess, but reasonable.

**Comment by squarooticus** [comment]
I read "1k packets" as "packets of size 1 KB". That explains the confusion. Anyway, I think I've covered this in an understandable way without reference to specific numbers, but feel free to reopen this issue if you think otherwise.
